### PR TITLE
Added Image Slider

### PR DESCRIPTION
**Pull request by Mahich123**
Added CSS Image slider folders updated . Can you check the changes now ?

### CODE REVIEW

**Comment by irshadmd** [comment]
Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by Mahich123** [comment]
Okay

**Comment by Mahich123** [comment]
@irshadmd  Gif file of the preview has been included now .

**Comment by irshadmd** [comment]
> @irshadmd Gif file of the preview has been included now .

awesome

**Pull request merged**
