### PR TITLE
Music Store

### PR DESCRIPTION
**Pull request by Z3RO-O**

### CODE REVIEW

**Comment by irshadmd** [comment]
Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by Z3RO-O** [comment]
Now I have added demo.gif

**Comment by irshadmd** [comment]
> Now I have added demo.gif

its mp4 not gif, please fix it

**Comment by Z3RO-O** [comment]
Fixed the mp4 file and replaced it with gif

**Comment by irshadmd** [comment]
rename demo to demo.gif

**Pull request closed without merging**
