### PR TITLE
Created Circle Image Slider

### PR DESCRIPTION
**Pull request by Shrit1401**

### CODE REVIEW

**Comment by Shrit1401** [comment]
https://shrit1401.github.io/CircleImageSlider/ this is live preview, all is from pure CSS no JS and I have also pulled a request

**Comment by irshadmd** [comment]
great work 🚀

**Comment by irshadmd** [comment]
Please do one thing, create a demo folder inside "Circle Image Slider" and add a demo of your project named demo.gif

**Comment by Shrit1401** [comment]
oh yeah ill do it right now, is it has to be a gif can i put a png?

**Comment by irshadmd** [comment]
gif of changing the slider would be good

**Comment by irshadmd** [comment]
@Shrit1401 please add demo.gif

**Pull request closed without merging**
