### PR TITLE
added TodoList

### PR DESCRIPTION
**Pull request by Pritam0077**
I have added my Todolist project

### CODE REVIEW

**Review by irshadmd — CHANGES_REQUESTED** [review]
try to make it a bit more attractive add some CSS also if you are not using nav bar you can remove it.

**Comment by Pritam0077** [comment]
ok

**Comment by Pritam0077** [comment]
I have made the changes

**Comment by irshadmd** [comment]
add item not working

**Comment by Pritam0077** [comment]
it works after some time

**Comment by irshadmd** [comment]
> it works after some time

please fix it

**Pull request closed without merging**
