### PR TITLE
Spotify-clone

### PR DESCRIPTION
**Pull request by Morbius00**
Open Source Love

## SPOTIFY -CLONE
Screenshot 2022-10-05 100818

I want to create a Spotify Landing Page clone using this simple tech stacks :

<a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> css3   <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> html5 </a>   <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> javascript </a>
Hope you like my project #Hacktoberfest22
regards,

### CODE REVIEW

**Comment by irshadmd** [comment]
cool, Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by Morbius00** [comment]
demo file uploaded please check it once thank you

**Comment by irshadmd** [comment]
> demo file uploaded please check it once thank you

rename demo to "demo.gif" only

**Comment by Morbius00** [comment]
rename done to demo

**Pull request merged**
