### PR TITLE
Added a cooking website

### PR DESCRIPTION
**Pull request by zugzwang03**
I have added a cooking website with the name of simply recipes.
resolved issue #191

### CODE REVIEW

**Comment by irshadmd** [comment]
Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by zugzwang03** [comment]
Can you suggest a good website for screen recording in PC? @irshadmd

**Comment by zugzwang03** [comment]
yeah, all done !!

**Comment by irshadmd** [comment]
> yeah, all done !!

great

**Pull request merged**
