### PR TITLE
Background-Generator added

### PR DESCRIPTION
**Pull request by tokyo3001**
Background-generator added to the project. The background colour can be adjusted with a just a click.

### CODE REVIEW

**Comment by irshadmd** [comment]
remove node_modules folders

**Comment by irshadmd** [comment]
Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by irshadmd** [comment]
also remove package.json files

**Comment by tokyo3001** [comment]
@irshadmd Changes done as per your requirement. #94

**Pull request closed without merging**
