### PR TITLE
Creating New IOS Icons 

### PR DESCRIPTION
**Pull request by manni2000**
Please Merge New IOS Icons in HTML & CSS.
Sample ;
image

### CODE REVIEW

**Comment by irshadmd** [comment]
Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by manni2000** [comment]
I'm added demo Gif .. Sorry for low quality sir. 
Please Merge. 
Thank you

**Comment by irshadmd** [comment]
> I'm added demo Gif .. Sorry for low quality sir. Please Merge. Thank you

cool, just create demo folder and move demo there

**Comment by manni2000** [comment]
Done! Now Merge please

**Pull request merged**
