### PR TITLE
Digital Clock with dark mode

### PR DESCRIPTION
**Pull request by AbhiMishra-Now**
Screenshot (783)
Screenshot (782)

### CODE REVIEW

**Comment by irshadmd** [comment]
Cool, Please do one thing create a demo folder inside "Digital Clock" and add a gif of your project named demo.gif

**Comment by AbhiMishra-Now** [comment]
Done.

**Comment by irshadmd** [comment]
> Done.

good work 🚀

**Review by irshadmd — APPROVED** [review]

**Comment by AbhiMishra-Now** [comment]
✌🏼

**Pull request merged**
