### PR TITLE
added playDrum project (fixed files that were missing)

### PR DESCRIPTION
**Pull request by axshatj**
@irshadmd sorry for the inconvenience i forgot to git add file inside the playDrum folder fixed it now

### CODE REVIEW

**Comment by irshadmd** [comment]
> @irshadmd sorry for the inconvenience i forgot to git add file inside the playDrum folder fixed it now

no worries, Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by axshatj** [comment]
@irshadmd added gif

**Comment by irshadmd** [comment]
> @irshadmd added gif

format is not correct, also rename it to "demo.gif"

**Comment by axshatj** [comment]
@irshadmd updated pls check now

**Comment by irshadmd** [comment]
> @irshadmd updated pls check now

remove this file playDrum/Demo/DemoDrum.webm

**Comment by axshatj** [comment]
@irshadmd done

**Pull request merged**
