### PR TITLE
Add Pixi connect balls game

### PR DESCRIPTION
**Pull request by toukirkhan**
I have created a connect ball game named "Pixi" using HTML, CSS, Javascript and pixi.js as the name justifies. Basically you have to avoid blue evil balls and connect white good balls to increase your points and continue the game.

### CODE REVIEW

**Comment by irshadmd** [comment]
Please create a demo folder inside "pixi game" and add a working demo of your project named demo.gif

**Review by irshadmd — CHANGES_REQUESTED** [review]
demo is not in gif format

**Comment by toukirkhan** [comment]
Okay wait

**Comment by toukirkhan** [comment]
@irshadmd I uploaded the gif file

**Review by irshadmd — APPROVED** [review]
good work

**Pull request merged**
