### PR TITLE
meditation app

### PR DESCRIPTION
**Pull request by Akayush-17**
User can listen to different music in order to relax mind

### CODE REVIEW

**Comment by irshadmd** [comment]
Please create a demo folder inside your project and add a working demo of your project named demo.gif

**Comment by Akayush-17** [comment]
> Please create a demo folder inside your project and add a working demo of your project named demo.gif

Hey I have added the demo file you can check that

**Comment by irshadmd** [comment]
meditation app demo is not in proper format also rename quiz app demo to "demo.gif"

**Comment by Akayush-17** [comment]
> meditation app demo is not in proper format also rename quiz app demo to "demo.gif"

Now the demo file is working. please ignore the quiz app it accidently got merged to this pull request

**Comment by irshadmd** [comment]
great 👍🏻

**Pull request merged**
