### PR TITLE
Pokemons

### PR DESCRIPTION
**Pull request by GeekkyCoder**
All the Pokemons from Japanese Manga Series!

### CODE REVIEW

**Comment by irshadmd** [comment]
Looks good, Please do one thing create a demo folder inside "Pokemons" and add a gif of your project named demo.gif

**Comment by GeekkyCoder** [comment]
Ok i will do it! Thanks Irshad

**Comment by irshadmd** [comment]
@GeekkyCoder please add demo.gif

**Comment by GeekkyCoder** [comment]
sure i almost forget it! sorry for that

**Pull request merged**
