### PR TITLE
Headphone Website

### PR DESCRIPTION
**Pull request by AyushSingh-github**

### CODE REVIEW

**Comment by irshadmd** [comment]
great work 🚀

**Comment by irshadmd** [comment]
Please do one thing create a demo folder inside "Headphone Transition Website" and add a 3-5 sec demo of your project named demo.gif

**Comment by AyushSingh-github** [comment]
ok

**Comment by AyushSingh-github** [comment]
i couldn't make a gif ,so i just recorded a vdo and pushed my the mkv type file using obs in "Headphone Transition Website".
Hope it helps !

**Pull request merged**
