### PR TITLE
Age Calculator

### PR DESCRIPTION
**Pull request by Shaba1406**
Description
- This is an Age Calculator project
- Tech used :- HTML,CSS and Javascript
- You can calculate your age through this, the only thing you have to do is to enter your DOB and it will give you the output 

Screenshot

|#screenshot 1|

Visual Studio Code 05-10-2022 12_06_07

|#screenhot 2|

Age Calculator - Google Chrome 05-10-2022 12_10_00

### CODE REVIEW

**Comment by Shaba1406** [comment]
@irshadmd  Kindly review my PR

**Comment by irshadmd** [comment]
looks good, Please create a demo folder inside "Age Calculator" and add a working demo of your project named demo.gif

**Comment by Shaba1406** [comment]
@irshadmd Done with the changes

**Comment by irshadmd** [comment]
please create demo folder and then move demo.gif there

**Comment by Shaba1406** [comment]
@irshadmd  Now it is okay ?

**Comment by irshadmd** [comment]
> @irshadmd Now it is okay ?

🚀

**Pull request merged**
