### PR TITLE
added color picker game

### PR DESCRIPTION
**Pull request by stubborn-1508**
This request is in regards to issue #134 . Last time I created a small glitch by creating a git subfolder. I resolved it and made a new pull request. Please merge the request.

### CODE REVIEW

**Comment by stubborn-1508** [comment]
Sir,please can you merge the request, I already all the necessary files for issue #134 .

**Comment by stubborn-1508** [comment]
I added it.

**Comment by irshadmd** [comment]
Screenshot 2022-10-08 at 1 00 09 AM
please fix name "demo.gif" also create demo folder then move demo there

**Comment by stubborn-1508** [comment]
I fixed the name and created demo folder and also added easy and hard mode screenshots there. Please merge the request.

**Pull request closed without merging**
