### PR TITLE
Speech to text

### PR DESCRIPTION
**Pull request by sonalij06**
Added gif

### CODE REVIEW

**Comment by irshadmd** [comment]
please convert mp4 to gif, also create demo folder and add there as demo.gif, you can use online mp4 to gif converter

**Review by irshadmd — APPROVED** [review]
awesome 🚀

**Comment by sonalij06** [comment]
I think i have created one more pr, do i need to delete??

**Comment by irshadmd** [comment]
> I think i have created one more pr, do i need to delete??

I closed already

**Pull request merged**
